### ISSUE TITLE
Enabler: Update Node

### ISSUE THREAD

**Issue by blairlearn** [NCIOCPL/elastic-tools#8]
# Upgrade to current Node LTS version

Make any changes needed to work with the current LTS version of Node. 

> **ESTIMATE** TBD

**Comment by blairl-nih** [comment]
No changes needed.  Works with Node 16 (current LTS) and 18 (LTS starts 2023-10-18).

**Comment by blairlearn** [comment]
No changes needed. Works with Node 16 (current LTS) and 18 (LTS scheduled for 2023-10-18).
